services:
    PoP\Pages\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Pages\Conditional\API\RouteModuleProcessors\:
        resource: '../src/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\Pages\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../src/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true
